// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.devoxx.model.json;

public class TalkBuilder extends TalkBuilderBase<TalkBuilder> {
	public static TalkBuilder talk() {
		return new TalkBuilder();
	}

	public TalkBuilder() {
		super(new Talk());
	}

	public Talk build() {
		return getInstance();
	}
}

class TalkBuilderBase<GeneratorT extends TalkBuilderBase<GeneratorT>> {
	private Talk instance;

	protected TalkBuilderBase(Talk aInstance) {
		instance = aInstance;
	}

	protected Talk getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withSummary(String aValue) {
		instance.setSummary(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withTags(Tag[] aValue) {
		instance.setTags(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withSpeaker(String aValue) {
		instance.setSpeaker(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withTrack(String aValue) {
		instance.setTrack(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withType(String aValue) {
		instance.setType(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withSpeakers(EmbeddedSpeaker[] aValue) {
		instance.setSpeakers(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withId(Long aValue) {
		instance.setId(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withTitle(String aValue) {
		instance.setTitle(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withSpeakerUri(String aValue) {
		instance.setSpeakerUri(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withSpeakerId(String aValue) {
		instance.setSpeakerId(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withExperience(String aValue) {
		instance.setExperience(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withLanguage(String aValue) {
		instance.setLanguage(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withRoom(String aValue) {
		instance.setRoom(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withNbVotes(Long aValue) {
		instance.setNbVotes(aValue);

		return (GeneratorT) this;
	}
}
